"""
API Gateway & Orchestration Layer
Generated by SkillOpt Autonomous IDE Engine
"""
from typing import Dict, Any
from engine import AutonomousEngine

class APIGateway:
    def __init__(self):
        self.engine = AutonomousEngine()

    def handle_request(self, endpoint: str, payload: Dict[str, Any]) -> Dict[str, Any]:
        if endpoint == "/api/dispatch":
            task_id = payload.get("task_id", "default_task")
            data = payload.get("data", {})
            return self.engine.execute_step(task_id, data)
        elif endpoint == "/api/health":
            return {"status": "HEALTHY", "processed_events": self.engine.processed_events}
        return {"error": "Endpoint not found", "code": 404}
