"""
FastMCP Server Template - Model Context Protocol Server
Generated by mcp_builder.py
"""
import os
import sys
import json
from typing import Dict, Any

class MCPServer:
    def __init__(self, name: str = "demo_calculator"):
        self.name = name
        self.tools = {}
        self._register_default_tools()

    def register_tool(self, name: str, func):
        self.tools[name] = func

    def _register_default_tools(self):
        def add(a: float, b: float) -> float:
            """Adds two numbers."""
            return a + b

        def echo(message: str) -> str:
            """Echoes the input message."""
            return f"Echo: {message}"

        self.register_tool("add", add)
        self.register_tool("echo", echo)

    def handle_request(self, request_json: str) -> str:
        try:
            req = json.loads(request_json)
            method = req.get("method")
            params = req.get("params", {})

            if method == "tools/list":
                tool_list = [
                    {"name": name, "description": func.__doc__ or ""}
                    for name, func in self.tools.items()
                ]
                return json.dumps({"result": {"tools": tool_list}})

            elif method == "tools/call":
                name = params.get("name")
                args = params.get("arguments", {})
                if name in self.tools:
                    res = self.tools[name](**args)
                    return json.dumps({"result": {"content": [{"type": "text", "text": str(res)}]}})
                return json.dumps({"error": f"Tool '{name}' not found"})

            return json.dumps({"error": f"Unknown method '{method}'"})
        except Exception as e:
            return json.dumps({"error": str(e)})

if __name__ == "__main__":
    server = MCPServer()
    print(f"Server '{server.name}' initialized with {len(server.tools)} tools.")
