import os
import sys
import json
import subprocess
import argparse

MCP_SERVER_TEMPLATE = '''"""
FastMCP Server Template - Model Context Protocol Server
Generated by mcp_builder.py
"""
import os
import sys
import json
from typing import Dict, Any

class MCPServer:
    def __init__(self, name: str = "{server_name}"):
        self.name = name
        self.tools = {{}}
        self._register_default_tools()

    def register_tool(self, name: str, func):
        self.tools[name] = func

    def _register_default_tools(self):
        def add(a: float, b: float) -> float:
            """Adds two numbers."""
            return a + b

        def echo(message: str) -> str:
            """Echoes the input message."""
            return f"Echo: {{message}}"

        self.register_tool("add", add)
        self.register_tool("echo", echo)

    def handle_request(self, request_json: str) -> str:
        try:
            req = json.loads(request_json)
            method = req.get("method")
            params = req.get("params", {{}})

            if method == "tools/list":
                tool_list = [
                    {{"name": name, "description": func.__doc__ or ""}}
                    for name, func in self.tools.items()
                ]
                return json.dumps({{"result": {{"tools": tool_list}}}})

            elif method == "tools/call":
                name = params.get("name")
                args = params.get("arguments", {{}})
                if name in self.tools:
                    res = self.tools[name](**args)
                    return json.dumps({{"result": {{"content": [{{"type": "text", "text": str(res)}}]}}}})
                return json.dumps({{"error": f"Tool '{{name}}' not found"}})

            return json.dumps({{"error": f"Unknown method '{{method}}'"}})
        except Exception as e:
            return json.dumps({{"error": str(e)}})

if __name__ == "__main__":
    server = MCPServer()
    print(f"Server '{{server.name}}' initialized with {{len(server.tools)}} tools.")
'''

TEST_SUITE_TEMPLATE = '''"""
Unit Tests for Generated MCP Server
"""
import unittest
import json
from {server_module} import MCPServer

class TestMCPServer(unittest.TestCase):
    def setUp(self):
        self.server = MCPServer()

    def test_list_tools(self):
        response = json.loads(self.server.handle_request('{{\"method\": \"tools/list\"}}'))
        self.assertIn("result", response)
        tools = response["result"]["tools"]
        tool_names = [t["name"] for t in tools]
        self.assertIn("add", tool_names)
        self.assertIn("echo", tool_names)

    def test_call_add_tool(self):
        req = json.dumps({{
            "method": "tools/call",
            "params": {{"name": "add", "arguments": {{"a": 5, "b": 10}}}}
        }})
        response = json.loads(self.server.handle_request(req))
        self.assertIn("result", response)
        res_text = response["result"]["content"][0]["text"]
        self.assertEqual(res_text, "15")

if __name__ == "__main__":
    unittest.main()
'''

def build_and_verify_mcp_server(server_name: str, out_dir: str = "."):
    print(f"\n{'='*60}")
    print(f"🛠️ MCP Server Generator & Verification Harness")
    print(f"   Server Name: {server_name}")
    print(f"   Output Directory: {out_dir}")
    print(f"{'='*60}\n")

    os.makedirs(out_dir, exist_ok=True)
    server_filename = f"{server_name}_server.py"
    test_filename = f"test_{server_name}_server.py"

    server_path = os.path.join(out_dir, server_filename)
    test_path = os.path.join(out_dir, test_filename)

    # Write server file
    server_code = MCP_SERVER_TEMPLATE.format(server_name=server_name)
    with open(server_path, "w") as f:
        f.write(server_code)
    print(f"  ✅ Generated server code at {server_path}")

    # Write test file
    test_code = TEST_SUITE_TEMPLATE.format(server_module=f"{server_name}_server")
    with open(test_path, "w") as f:
        f.write(test_code)
    print(f"  ✅ Generated test harness at {test_path}")

    # Step 1: Syntax / Compilation Check
    print("\n🔍 Running Step 1: Subprocess Syntax Verification...")
    res_compile = subprocess.run([sys.executable, "-m", "py_compile", server_path], capture_output=True, text=True)
    if res_compile.returncode != 0:
        print(f"❌ Syntax Error in {server_filename}: {res_compile.stderr.strip()}")
        return False

    print("   ✅ Syntax Verification PASSED!")

    # Step 2: Run Unit Test Harness
    print("\n🧪 Running Step 2: Unit Test Verification...")
    res_test = subprocess.run([sys.executable, test_path], capture_output=True, text=True)
    if res_test.returncode == 0:
        print("   🎉 All MCP Server Unit Tests PASSED!")
        print(f"\n✨ MCP Server '{server_name}' successfully built and verified!")
        return True
    else:
        print(f"❌ Unit Test Failure: {res_test.stderr.strip()}")
        return False

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server Builder & Verifier")
    parser.add_argument("name", type=str, nargs="?", default="mcp_app", help="Server name prefix")
    parser.add_argument("--out", type=str, default=".", help="Output directory")
    args = parser.parse_args()

    build_and_verify_mcp_server(args.name, args.out)
