"""
Data Models for Distributed Architecture
Generated by SkillOpt Autonomous IDE Engine
"""
from typing import Dict, List, Optional, Any
import time

class SystemEvent:
    def __init__(self, event_id: str, event_type: str, payload: Dict[str, Any], timestamp: Optional[float] = None):
        self.event_id = event_id
        self.event_type = event_type
        self.payload = payload
        self.timestamp = timestamp or time.time()

    def to_dict(self) -> Dict[str, Any]:
        return {
            "event_id": self.event_id,
            "event_type": self.event_type,
            "payload": self.payload,
            "timestamp": self.timestamp
        }

class TaskState:
    def __init__(self, task_id: str, status: str = "INITIALIZED"):
        self.task_id = task_id
        self.status = status
        self.history: List[SystemEvent] = []

    def transition(self, new_status: str, reason: str = ""):
        self.status = new_status
        self.history.append(SystemEvent(f"evt-{len(self.history)+1}", "STATE_CHANGE", {"status": new_status, "reason": reason}))
