import os
import sys
import json
import time
import subprocess
import argparse
import ast
from typing import List, Dict, Any
from urllib.request import Request, urlopen

# Default server URLs (compatible with local MLX / OpenAI-compatible endpoints)
PLANNER_URL = os.environ.get("PLANNER_URL", "http://localhost:8800/v1")
CODER_URL = os.environ.get("CODER_URL", "http://localhost:8800/v1")
DPO_LOG_PATH = os.environ.get("DPO_LOG_PATH", "/Users/adarrsh/workspace/dpo_logs.jsonl")

PLANNER_SYSTEM_PROMPT = """You are Gemma-4, a Master Software Architect. 
Given a high-level user goal, decompose it into a structured list of atomic code generation subtasks.
You MUST respond ONLY with a valid JSON array of objects, where each object has:
- "step_id": integer step number
- "description": clear specification of what code to write or edit
- "target_file": relative file path where code should be written
- "test_cmd": (optional) command to verify this step (e.g., "python -m py_compile main.py")

Example output format:
[
  {"step_id": 1, "description": "Write a math module with add and subtract functions.", "target_file": "math_utils.py", "test_cmd": "python -m py_compile math_utils.py"}
]
Do not include markdown code fences or explanatory text.
"""

CODER_SYSTEM_PROMPT = """You are Ornith, an Expert AI Coder.
Generate only valid, clean, self-contained Python code based on the task specification.
Do not include conversational filler or markdown fences. Output strictly raw executable code.
"""

REVIEWER_SYSTEM_PROMPT = """You are a strict Code Reviewer AI.
Given a task description, the target file, and the code generated by another AI, you must verify if the code is correct, complete, and satisfies the task.
If it is perfect and satisfies the task, respond with exactly: PASSED
If it has issues, bugs, or misses requirements, respond with a concise explanation of the errors so the coder can fix them. Do not write the fixed code yourself.
"""

def query_model(base_url: str, system_prompt: str, user_prompt: str, model_name: str = "AtomicChat/Ornith-9B-MLX-6bit", vector: str = None, alpha: float = 1.0, layer: int = 16, max_retries: int = 3) -> str:
    url = f"{base_url}/chat/completions"
    payload = {
        "model": model_name,
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt}
        ],
        "temperature": 0.2,
        "max_tokens": 1024,
        "steering_vector": vector,
        "alpha": alpha,
        "target_layer": layer
    }
    
    for attempt in range(1, max_retries + 1):
        req = Request(url, data=json.dumps(payload).encode("utf-8"), headers={"Content-Type": "application/json"})
        try:
            with urlopen(req, timeout=45) as resp:
                data = json.loads(resp.read().decode("utf-8"))
                return data["choices"][0]["message"]["content"].strip()
        except Exception as e:
            print(f"⚠️ [Attempt {attempt}/{max_retries}] Model query timed out or failed ({e}). Retrying in 2s...", flush=True)
            time.sleep(2)
            
    print(f"❌ [Orchestrator Error] All {max_retries} attempts to contact model server failed.", flush=True)
    return "# Code generation timed out after multiple retries."

def log_dpo_pair(prompt: str, rejected: str, chosen: str, error: str):
    entry = {
        "prompt": prompt,
        "rejected": rejected,
        "chosen": chosen,
        "error": error
    }
    with open(DPO_LOG_PATH, "a") as f:
        f.write(json.dumps(entry, ensure_ascii=False) + "\n")
    print(f"  [DPO Flywheel] Logged failure/recovery pair to {DPO_LOG_PATH}", flush=True)

def update_state_memory(goal: str, tasks: List[Dict[str, Any]], current_idx: int, message: str = ""):
    """Updates the STATE.md file so the user and loop have a persistent memory of progress."""
    state_content = f"# Loop Engineering State Memory\n\n**Goal**: {goal}\n**Status**: {message}\n\n## Tasks:\n"
    for i, task in enumerate(tasks):
        step_id = task.get('step_id')
        desc = task.get('description')
        if i < current_idx:
            status_char = "x"
        elif i == current_idx:
            status_char = "/"
        else:
            status_char = " "
        state_content += f"- [{status_char}] Step {step_id}: {desc}\n"
        
    try:
        with open("STATE.md", "w") as f:
            f.write(state_content)
    except Exception as e:
        print(f"Warning: Could not write STATE.md: {e}", flush=True)

def evaluate_code(code: str, desc: str, target_file: str) -> str:
    """Checker subagent: runs deterministic AST parse + semantic LLM review."""
    # 1. Deterministic AST syntax check
    try:
        ast.parse(code)
    except SyntaxError as e:
        return f"SyntaxError: {e}"
    
    # 2. Semantic LLM Review
    print(f"   🕵️‍♀️  [Checker] Reviewing code for semantic correctness...", flush=True)
    prompt = f"Task: {desc}\nTarget File: {target_file}\nGenerated Code:\n```python\n{code}\n```\nVerify if this code fulfills the task."
    review = query_model(CODER_URL, REVIEWER_SYSTEM_PROMPT, prompt)
    
    if "PASSED" in review.upper()[:20]:
        return "PASSED"
    return review

def run_task_graph(goal: str, vector: str = None, alpha: float = 1.0, layer: int = 16):
    print(f"\n{'='*60}", flush=True)
    print(f"🚀 Multi-Agent Orchestrator Starting Goal:", flush=True)
    print(f"   \"{goal}\"", flush=True)
    if vector:
        print(f"   🎛️ Active Steering: Vector='{vector}', Alpha={alpha}, Layer=L{layer}", flush=True)
    print(f"{'='*60}\n", flush=True)

    # Step 1: Planner decomposes goal
    print("🧠 [1/2] Gemma-4 (Planner) generating task graph...", flush=True)
    planner_response = query_model(PLANNER_URL, PLANNER_SYSTEM_PROMPT, f"User Goal: {goal}", vector=vector, alpha=alpha, layer=layer)
    
    if planner_response.startswith("```"):
        planner_response = planner_response.strip("`").removeprefix("json").strip()

    try:
        task_graph: List[Dict[str, Any]] = json.loads(planner_response)
    except Exception as e:
        print(f"❌ Failed to parse task graph JSON from Planner: {e}", flush=True)
        return

    print(f"✅ Planned {len(task_graph)} subtasks.", flush=True)
    update_state_memory(goal, task_graph, -1, "Planned tasks")

    try:
        with open("task_graph.json", "w") as f:
            json.dump({"goal": goal, "tasks": task_graph}, f, indent=2)
    except Exception:
        pass

    # Step 2: Evaluator-Optimizer Loop
    for i, task in enumerate(task_graph):
        step_id = task.get("step_id")
        desc = task.get("description")
        target_file = task.get("target_file")
        test_cmd = task.get("test_cmd")

        print(f"\n💻 [2/2] Ornith (Coder) executing Step {step_id}: {desc}", flush=True)
        update_state_memory(goal, task_graph, i, f"Working on step {step_id} (Attempt 1)")
        
        # Loop Engineering: Maker <-> Checker
        max_loop_iterations = 3
        code = ""
        current_prompt = f"Task: {desc}\nTarget File: {target_file}"
        
        for iteration in range(1, max_loop_iterations + 1):
            print(f"   📝 [Maker] Generating code (Attempt {iteration}/{max_loop_iterations})...", flush=True)
            code = query_model(CODER_URL, CODER_SYSTEM_PROMPT, current_prompt)
            
            if code.startswith("```"):
                lines = code.splitlines()
                if lines[0].startswith("```"): lines = lines[1:]
                if lines and lines[-1].startswith("```"): lines = lines[:-1]
                code = "\n".join(lines)
            
            # Run Checker Evaluator
            review_feedback = evaluate_code(code, desc, target_file)
            if review_feedback == "PASSED":
                print(f"   ✅ [Checker] Verification Passed! Code accepted.", flush=True)
                break
            else:
                print(f"   ❌ [Checker] Verification Failed:\n   {review_feedback.splitlines()[0][:100]}...", flush=True)
                if iteration < max_loop_iterations:
                    print(f"   🔄 [Loop] Feedback sent back to Maker.", flush=True)
                    # Accumulate context
                    current_prompt += f"\n\n--- PREVIOUS ATTEMPT FAILED ---\nCode:\n{code}\nFeedback:\n{review_feedback}\nFix the code based on the feedback."
                    # Log DPO for self-correction flywheel tracking
                    log_dpo_pair(desc, code, "", review_feedback)
                else:
                    print(f"   ⚠️ [Loop] Max iterations reached. Proceeding with last attempt.", flush=True)

        if target_file:
            os.makedirs(os.path.dirname(target_file) if os.path.dirname(target_file) else ".", exist_ok=True)
            with open(target_file, "w") as f:
                f.write(code)
            print(f"   💾 Saved output to {target_file}", flush=True)

        if test_cmd:
            exec_cmd = test_cmd.replace("python -m pytest", f"{sys.executable} -m unittest").replace("python ", f"{sys.executable} ")
            print(f"   🏃 Running manual test cmd: `{exec_cmd}`...", flush=True)
            res = subprocess.run(exec_cmd, shell=True, capture_output=True, text=True)
            if res.returncode == 0:
                print(f"   🎉 Manual Test Passed!", flush=True)
            else:
                print(f"   ❌ Manual Test Failed (code {res.returncode}): {res.stderr.strip()}", flush=True)

    update_state_memory(goal, task_graph, len(task_graph), "Execution Complete")
    print(f"\n{'='*60}", flush=True)
    print(f"✨ Goal Execution Complete!", flush=True)
    print(f"{'='*60}\n", flush=True)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Multi-Agent Orchestrator")
    parser.add_argument("goal", type=str, nargs="?", default="Create a simple python module named greeting.py that has a greet(name) function and a test command.", help="High-level goal for the agents")
    parser.add_argument("--vector", type=str, default=None, help="Steering vector name")
    parser.add_argument("--alpha", type=float, default=1.0, help="Steering alpha scaling factor")
    parser.add_argument("--layer", type=int, default=16, help="Target injection layer")
    args = parser.parse_args()

    run_task_graph(args.goal, vector=args.vector, alpha=args.alpha, layer=args.layer)
