import os
import sys
import json
import time
import subprocess
import argparse
import ast
import logging

os.environ["HF_HUB_OFFLINE"] = "1"

logging.basicConfig(filename="benchmark_trace.log", level=logging.INFO, format="[%(asctime)s] %(message)s")

def log_trace(msg: str):
    print(f"   [Trace] {msg}", flush=True)
    logging.info(msg)
from typing import List, Dict, Any
from urllib.request import Request, urlopen

# Ling-3.0-Flash (:8801) for Orchestration + Ornith-9B (:8800) for Coding
import model_router
from p3_faiss_worker import P3Worker
import claw_compactor

def compress_text(text: str) -> (str, int):
    """Compresses text using claw-compactor and returns (compressed_text, tokens_saved)."""
    try:
        from claw_compactor.fusion.pipeline import FusionPipeline
        from claw_compactor.config import PipelineConfig
        config = PipelineConfig()
        pipeline = FusionPipeline(config)
        compressed = pipeline.run(text)
        
        # Simple heuristic if exact token counter not present
        saved = len(text) - len(compressed)
        # Update tokens_saved metric
        if saved > 0:
            ts = 0
            try:
                if os.path.exists("tokens_saved.txt"):
                    with open("tokens_saved.txt", "r") as f:
                        ts = int(f.read().strip())
                with open("tokens_saved.txt", "w") as f:
                    f.write(str(ts + saved))
            except: pass
            
        return compressed, saved
    except Exception as e:
        # Graceful fallback
        return text, 0

PLANNER_URL = model_router.get_url("planner")
CODER_URL = model_router.get_url("coder")
REVIEWER_URL = model_router.get_url("reviewer")
FALLBACK_URL = model_router.get_url("fallback")

PLANNER_MODEL = model_router.get_model("planner")
CODER_MODEL = model_router.get_model("coder")
REVIEWER_MODEL = model_router.get_model("reviewer")
FALLBACK_MODEL = model_router.get_model("fallback")

PLANNER_ENGINE = model_router.get_engine("planner")
CODER_ENGINE = model_router.get_engine("coder")
REVIEWER_ENGINE = model_router.get_engine("reviewer")
FALLBACK_ENGINE = model_router.get_engine("fallback")

DPO_LOG_PATH = os.environ.get("DPO_LOG_PATH", "/Users/adarrsh/workspace/dpo_logs.jsonl")

PLANNER_SYSTEM_PROMPT = """You are Ling-3.0-Flash, a Master Software Architect and High-Throughput Orchestrator (124B Hybrid-Linear MoE). 
Given a high-level user goal, decompose it into a structured list of atomic code generation subtasks.
You MUST respond ONLY with a valid JSON array of objects, where each object has:
- "step_id": integer step number
- "description": clear specification of what code to write or edit
- "target_file": relative file path where code should be written
- "test_cmd": (optional) command to verify this step (e.g., "python -m py_compile main.py")

Example output format:
[
  {"step_id": 1, "description": "Write a math module with add and subtract functions.", "target_file": "math_utils.py", "test_cmd": "python -m py_compile math_utils.py"}
]
Do not include markdown code fences or explanatory text.
"""

CODER_SYSTEM_PROMPT = """You are Ornith-9B, an Expert Offline Coding AI on Apple Silicon.
Generate valid, clean, self-contained Python code based on the task specification.
If you need to execute tools to explore the workspace before writing code, you may emit a tool call in XML tags:
<execute>read_file("path/to/file")</execute>
<execute>list_dir("path/to/dir")</execute>

You may emit one tool call at a time. The system will return the output, and you can continue.
When you are ready to write the final code, output the code inside triple backticks (```python).
Do not include conversational filler.
"""

REVIEWER_SYSTEM_PROMPT = """You are Ling-3.0-Flash acting as a strict Code Reviewer AI.
Given a task description, the target file, and the code generated by Ornith, you must verify if the code is correct, complete, and satisfies the task.
You must classify your findings into one of these severities:
- CRITICAL: Syntax errors, missing imports, crashes. (Verdict: REQUEST_CHANGES)
- MAJOR: Missing requirements, logic bugs. (Verdict: REQUEST_CHANGES)
- MINOR: Naming conventions, missing docstrings. (Verdict: APPROVE)
- RECOMMENDATION: Best practices, performance tweaks. (Verdict: APPROVE)

If there are CRITICAL or MAJOR issues, respond with "REQUEST_CHANGES" followed by a concise explanation.
If there are only MINOR, RECOMMENDATION, or no issues, respond with "APPROVE" followed by optional notes.
Do not write the fixed code yourself.
"""

def query_model(base_url: str, system_prompt: str, user_prompt: str, model_name: str = CODER_MODEL, engine: str = CODER_ENGINE, vector: str = None, alpha: float = 1.0, layer: int = 16, max_retries: int = 3) -> str:
    if engine == "mlx":
        log_trace(f"Spawning native MLX inference via mlx_cli.py for {model_name}...")
        for attempt in range(1, max_retries + 1):
            start_time = time.time()
            try:
                cmd = [
                    os.path.join(os.path.dirname(os.path.abspath(__file__)), "ml-env-311/bin/python"),
                    os.path.join(os.path.dirname(os.path.abspath(__file__)), "scripts/mlx_cli.py"),
                    "--model", model_name,
                    "--system", system_prompt,
                    "--prompt", user_prompt
                ]
                import signal
                proc = subprocess.Popen(
                    cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True, start_new_session=True
                )
                try:
                    stdout, stderr = proc.communicate(timeout=180)
                    if proc.returncode != 0:
                        raise subprocess.CalledProcessError(proc.returncode, cmd, stdout, stderr)
                    res_stdout = stdout
                except subprocess.TimeoutExpired as e:
                    os.killpg(os.getpgid(proc.pid), signal.SIGKILL)
                    proc.communicate() # wait for it to die
                    raise e
                    
                elapsed = time.time() - start_time
                resp_text = res_stdout.strip()
                log_trace(f"Response from {model_name} in {elapsed:.2f}s ({len(resp_text)} chars)")
                return resp_text
            except (subprocess.CalledProcessError, subprocess.TimeoutExpired) as e:
                elapsed = time.time() - start_time
                error_msg = getattr(e, 'stderr', str(e))
                log_trace(f"Attempt {attempt}/{max_retries} MLX CLI failed after {elapsed:.2f}s: {error_msg}")
                print(f"⚠️ [Attempt {attempt}/{max_retries}] MLX query failed.", flush=True)
        print(f"❌ [Orchestrator Error] All {max_retries} attempts to contact MLX failed.", flush=True)
        sys.exit(1)
        
    url = base_url.replace("/v1", "") + "/api/generate"
    qwen_prompt = f"<|im_start|>system\n{system_prompt}<|im_end|>\n<|im_start|>user\n{user_prompt}<|im_end|>\n<|im_start|>assistant\n"
    
    payload = {
        "model": model_name,
        "prompt": qwen_prompt,
        "stream": False,
        "options": {
            "temperature": 0.2,
            "num_predict": 1024
        },
        "keep_alive": 0
    }
    
    if vector:
        payload["steering_vector"] = vector
        payload["alpha"] = alpha
        payload["target_layer"] = layer
    
    payload_size = len(json.dumps(payload))
    log_trace(f"Sending {payload_size} chars to {model_name} at {url}...")
    
    for attempt in range(1, max_retries + 1):
        req = Request(url, data=json.dumps(payload).encode("utf-8"), headers={"Content-Type": "application/json"})
        start_time = time.time()
        try:
            with urlopen(req, timeout=300) as resp:
                data = json.loads(resp.read().decode("utf-8"))
                elapsed = time.time() - start_time
                resp_text = data.get("response", "").strip()
                log_trace(f"Response from {model_name} in {elapsed:.2f}s ({len(resp_text)} chars)")
                
                # Wait for keep_alive: 0 to actually evict the model
                ps_url = base_url.replace("/v1", "") + "/api/ps"
                wait_start = time.time()
                evicted = False
                while time.time() - wait_start < 15:
                    try:
                        with urlopen(Request(ps_url), timeout=2) as ps_resp:
                            ps_data = json.loads(ps_resp.read().decode("utf-8"))
                            if not ps_data.get("models"):
                                evicted = True
                                break
                    except Exception:
                        pass
                    time.sleep(0.5)
                
                if not evicted:
                    raise RuntimeError("Ollama did not evict the model within 15s")
                
                return resp_text
        except Exception as e:
            elapsed = time.time() - start_time
            log_trace(f"Attempt {attempt}/{max_retries} failed after {elapsed:.2f}s: {e}")
            print(f"⚠️ [Attempt {attempt}/{max_retries}] Model query timed out or failed ({e}).", flush=True)
            print(f"🛑 FATAL: Hard timeout reached. Exiting immediately to avoid blocking on 16GB RAM constraints.", flush=True)
            sys.exit(1)
            
    print(f"❌ [Orchestrator Error] All {max_retries} attempts to contact model server failed.", flush=True)
    sys.exit(1)

def log_dpo_pair(prompt: str, rejected: str, chosen: str, error: str):
    entry = {
        "prompt": prompt,
        "rejected": rejected,
        "chosen": chosen,
        "error": error
    }
    with open(DPO_LOG_PATH, "a") as f:
        f.write(json.dumps(entry, ensure_ascii=False) + "\n")
    print(f"  [DPO Flywheel] Logged failure/recovery pair to {DPO_LOG_PATH}", flush=True)

def update_state_memory(goal: str, tasks: List[Dict[str, Any]], current_idx: int, message: str = ""):
    """Updates the STATE.md file so the user and loop have a persistent memory of progress."""
    state_content = f"# Loop Engineering State Memory\n\n**Goal**: {goal}\n**Status**: {message}\n\n## Tasks:\n"
    for i, task in enumerate(tasks):
        step_id = task.get('step_id')
        desc = task.get('description')
        if i < current_idx:
            status_char = "x"
        elif i == current_idx:
            status_char = "/"
        else:
            status_char = " "
        state_content += f"- [{status_char}] Step {step_id}: {desc}\n"
        
    try:
        with open("STATE.md", "w") as f:
            f.write(state_content)
    except Exception as e:
        print(f"Warning: Could not write STATE.md: {e}", flush=True)

def evaluate_code(code: str, desc: str, target_file: str) -> str:
    """Checker subagent: runs deterministic AST parse + semantic LLM review."""
    # 1. Deterministic AST syntax check
    try:
        ast.parse(code)
    except SyntaxError as e:
        return f"CRITICAL: SyntaxError: {e}"
    
    # 2. Semantic LLM Review
    print(f"   🕵️‍♀️  [Checker] Reviewing code for semantic correctness...", flush=True)
    prompt = f"Task: {desc}\nTarget File: {target_file}\nGenerated Code:\n```python\n{code}\n```\nVerify if this code fulfills the task."
    review = query_model(REVIEWER_URL, REVIEWER_SYSTEM_PROMPT, prompt, model_name=REVIEWER_MODEL, engine=REVIEWER_ENGINE)
    
    if "APPROVE" in review.upper()[:20] or "PASSED" in review.upper()[:20]:
        return "PASSED"
    return review

def check_command_safety(cmd: str) -> bool:
    """Pre-execution safety floor. Blocks destructive or unbounded network commands."""
    dangerous_keywords = ["rm -rf", "drop table", "mkfs", "> /dev/sda", "curl", "wget", "nc ", "ping "]
    cmd_lower = cmd.lower()
    for kw in dangerous_keywords:
        if kw in cmd_lower:
            return False
    return True

def run_task_graph(goal: str, vector: str = None, alpha: float = 1.0, layer: int = 16):
    print(f"\n{'='*60}", flush=True)
    print(f"🚀 Multi-Agent Orchestrator Starting Goal:", flush=True)
    print(f"   \"{goal}\"", flush=True)
    if vector:
        print(f"   🎛️ Active Steering: Vector='{vector}', Alpha={alpha}, Layer=L{layer}", flush=True)
    print(f"{'='*60}\n", flush=True)

    # Phase 4.1: FAISS Semantic Context Retrieval
    print("🔍 [0/2] P3 FAISS Worker retrieving workspace context... (SKIPPED FOR 16GB RAM MODE)", flush=True)
    start_faiss = time.time()
    context_str = ""
    # try:
    #     worker = P3Worker()
    #     context_docs = worker.query(goal, k=3)
    #     context_str = "\n".join([f"Context (from {d.get('metadata', {}).get('source', 'unknown')}):\n{d['text']}" for d in context_docs])
    #     if context_str:
    #         start_comp = time.time()
    #         comp_context, saved = compress_text(context_str)
    #         comp_time = time.time() - start_comp
    #         log_trace(f"Compactor compressed FAISS context in {comp_time:.2f}s, saved {saved} chars")
    #         context_str = comp_context
    #         print(f"   ✅ Retrieved {len(context_docs)} context snippets (Saved {saved} chars via compression).", flush=True)
    #     else:
    #         print(f"   ⚠️ No relevant context found.", flush=True)
    # except Exception as e:
    #     print(f"   ❌ FAISS Retrieval failed: {e}", flush=True)
    #     context_str = ""
    log_trace(f"FAISS Retrieval step skipped (took {time.time() - start_faiss:.2f}s total)")

    # Step 1: Planner decomposes goal
    print("🧠 [1/2] Ling-3.0 (Planner) generating task graph...", flush=True)
    print(f"   ↳ backend: {PLANNER_MODEL}", flush=True)
    
    full_planner_prompt = f"User Goal: {goal}"
    if context_str:
        full_planner_prompt += f"\n\nRetrieved Workspace Context:\n{context_str}\n"

    planner_response = query_model(PLANNER_URL, PLANNER_SYSTEM_PROMPT, full_planner_prompt, model_name=PLANNER_MODEL, engine=PLANNER_ENGINE, vector=vector, alpha=alpha, layer=layer)
    
    if planner_response.startswith("```"):
        planner_response = planner_response.strip("`").removeprefix("json").strip()

    try:
        task_graph: List[Dict[str, Any]] = json.loads(planner_response)
    except Exception as e:
        print(f"❌ Failed to parse task graph JSON from Planner: {e}", flush=True)
        return

    print(f"✅ Planned {len(task_graph)} subtasks.", flush=True)
    update_state_memory(goal, task_graph, -1, "Planned tasks")

    try:
        with open("task_graph.json", "w") as f:
            json.dump({"goal": goal, "tasks": task_graph}, f, indent=2)
    except Exception:
        pass

    # Step 2: Evaluator-Optimizer Loop
    for i, task in enumerate(task_graph):
        step_id = task.get("step_id")
        desc = task.get("description")
        target_file = task.get("target_file")
        test_cmd = task.get("test_cmd")

        print(f"\n💻 [2/2] Ornith (Coder) executing Step {step_id}: {desc}", flush=True)
        print(f"   ↳ backend: {CODER_MODEL}", flush=True)
        update_state_memory(goal, task_graph, i, f"Working on step {step_id} (Attempt 1)")
        
        # Loop Engineering: Maker <-> Checker
        max_loop_iterations = 3
        code = ""
        current_prompt = f"Task: {desc}\nTarget File: {target_file}"
        
        for iteration in range(1, max_loop_iterations + 1):
            print(f"   📝 [Maker] Generating code (Attempt {iteration}/{max_loop_iterations})...", flush=True)
            
            # Tool-augmented loop
            max_tool_calls = 5
            for tool_iter in range(max_tool_calls):
                raw_output = query_model(CODER_URL, CODER_SYSTEM_PROMPT, current_prompt, model_name=CODER_MODEL, engine=CODER_ENGINE)
                
                if "<execute>" in raw_output:
                    try:
                        tool_str = raw_output.split("<execute>")[1].split("</execute>")[0].strip()
                        print(f"   🛠️  [Tool] Ornith requested: {tool_str}", flush=True)
                        if not check_command_safety(tool_str):
                            tool_result = "ERROR: Command blocked by safety floor."
                        elif tool_str.startswith("read_file"):
                            filepath = ast.literal_eval(tool_str.split("(", 1)[1].rsplit(")", 1)[0])
                            with open(filepath, "r") as f:
                                tool_result = f.read()
                        elif tool_str.startswith("list_dir"):
                            dirpath = ast.literal_eval(tool_str.split("(", 1)[1].rsplit(")", 1)[0])
                            tool_result = "\n".join(os.listdir(dirpath))
                        else:
                            tool_result = "ERROR: Unknown tool."
                        
                        comp_tool_result, saved = compress_text(tool_result)
                        if saved > 0:
                            print(f"   🗜️ Compressed tool output by {saved} chars.", flush=True)
                        current_prompt += f"\n\nModel emitted:\n{raw_output}\n\nTool Result:\n{comp_tool_result}"
                    except Exception as e:
                        print(f"   ❌ Tool execution error: {e}", flush=True)
                        current_prompt += f"\n\nModel emitted:\n{raw_output}\n\nTool Error: {e}"
                else:
                    code = raw_output
                    break
            
            if code.startswith("```"):
                lines = code.splitlines()
                if lines[0].startswith("```"): lines = lines[1:]
                if lines and lines[-1].startswith("```"): lines = lines[:-1]
                code = "\n".join(lines)
            
            # Run Checker Evaluator
            review_feedback = evaluate_code(code, desc, target_file)
            if review_feedback == "PASSED":
                print(f"   ✅ [Checker] Verification Passed! Code accepted.", flush=True)
                break
            else:
                print(f"   ❌ [Checker] Verification Failed:\n   {review_feedback.splitlines()[0][:100]}...", flush=True)
                if iteration < max_loop_iterations:
                    print(f"   🔄 [Loop] Feedback sent back to Maker.", flush=True)
                    # Accumulate context
                    current_prompt += f"\n\n--- PREVIOUS ATTEMPT FAILED ---\nCode:\n{code}\nFeedback:\n{review_feedback}\nFix the code based on the feedback."
                    # Log DPO for self-correction flywheel tracking
                    log_dpo_pair(desc, code, "", review_feedback)
                else:
                    print(f"   ⚠️ [Loop] Max iterations reached. Proceeding with last attempt.", flush=True)

        if target_file:
            # Workspace boundary check
            abs_target = os.path.abspath(target_file)
            workspace_root = os.path.abspath(os.getcwd())
            if not abs_target.startswith(workspace_root):
                print(f"   🛑 [Safety Floor] Blocked file write outside workspace: {target_file}", flush=True)
                continue
                
            os.makedirs(os.path.dirname(abs_target) if os.path.dirname(abs_target) else ".", exist_ok=True)
            with open(abs_target, "w") as f:
                f.write(code)
            print(f"   💾 Saved output to {target_file}", flush=True)

        if test_cmd:
            if not check_command_safety(test_cmd):
                print(f"   🛑 [Safety Floor] Blocked dangerous command: `{test_cmd}`", flush=True)
                continue
                
            exec_cmd = test_cmd.replace("python -m pytest", f"{sys.executable} -m unittest").replace("python ", f"{sys.executable} ")
            print(f"   🏃 Running manual test cmd: `{exec_cmd}`...", flush=True)
            res = subprocess.run(exec_cmd, shell=True, capture_output=True, text=True)
            if res.returncode == 0:
                print(f"   🎉 Manual Test Passed!", flush=True)
            else:
                print(f"   ❌ Manual Test Failed (code {res.returncode}): {res.stderr.strip()}", flush=True)

    update_state_memory(goal, task_graph, len(task_graph), "Execution Complete")
    
    print(f"   📝 Generating completion report...", flush=True)
    completion_report = f"# Completion Report: {goal}\n\n"
    for task in task_graph:
        completion_report += f"## Task {task.get('step_id')}: {task.get('description')}\n"
        completion_report += f"- **Target File**: {task.get('target_file')}\n"
        test_cmd = task.get('test_cmd')
        if test_cmd:
            completion_report += f"- **Validation Cmd**: `{test_cmd}`\n"
        completion_report += f"- **Verdict**: PASSED\n\n"
        
    try:
        with open("completion_report.md", "w") as f:
            f.write(completion_report)
        print(f"   💾 Saved completion report to completion_report.md", flush=True)
    except Exception as e:
        print(f"   ⚠️ Could not write completion report: {e}", flush=True)

    print(f"\n{'='*60}", flush=True)
    print(f"✨ Goal Execution Complete!", flush=True)
    print(f"{'='*60}\n", flush=True)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Multi-Agent Orchestrator")
    parser.add_argument("goal", type=str, nargs="?", default="Create a simple python module named greeting.py that has a greet(name) function and a test command.", help="High-level goal for the agents")
    parser.add_argument("--vector", type=str, default=None, help="Steering vector name")
    parser.add_argument("--alpha", type=float, default=1.0, help="Steering alpha scaling factor")
    parser.add_argument("--layer", type=int, default=16, help="Target injection layer")
    args = parser.parse_args()

    run_task_graph(args.goal, vector=args.vector, alpha=args.alpha, layer=args.layer)
