"""
Comprehensive End-to-End System Test Suite
Generated by SkillOpt Autonomous IDE Engine
"""
import unittest
from models import SystemEvent, TaskState
from engine import AutonomousEngine
from app_gateway import APIGateway

class TestAutonomousSystem(unittest.TestCase):
    def test_models_lifecycle(self):
        task = TaskState("test-001")
        self.assertEqual(task.status, "INITIALIZED")
        task.transition("ACTIVE", "Testing transition")
        self.assertEqual(task.status, "ACTIVE")
        self.assertEqual(len(task.history), 1)

    def test_engine_execution(self):
        eng = AutonomousEngine()
        res = eng.execute_step("eng-100", {"key": "value"})
        self.assertEqual(res["status"], "COMPLETED")
        self.assertEqual(res["result"]["key"], "processed_value")

    def test_gateway_dispatch(self):
        gw = APIGateway()
        health = gw.handle_request("/api/health", {})
        self.assertEqual(health["status"], "HEALTHY")
        dispatch = gw.handle_request("/api/dispatch", {"task_id": "dispatch-01", "data": {"a": 1}})
        self.assertEqual(dispatch["status"], "COMPLETED")

if __name__ == "__main__":
    unittest.main()
