"""
Structured task ledger inspired by Claude Code Harness's Plans.md and 5-verb delivery loop.
Machine-parseable Markdown task tracking with drift detection between plan and filesystem state.
"""
import re
import json
import time
from pathlib import Path
from dataclasses import dataclass, field, asdict
from typing import List, Dict, Optional, Union, Any
from contracts import TaskLedger, TaskSpecData, DriftReport

@dataclass
class TaskSpec(TaskSpecData):
    pass


class MarkdownTaskLedger:
    """Writes, parses, and synchronizes Plans.md-style task tables."""

    def __init__(self, path: Union[str, Path] = "Plans.md"):
        self.path = Path(path)
        self._tasks: Dict[str, TaskSpec] = {}
        if self.path.exists():
            self._load_from_file()

    def add_task(self, task: Union[TaskSpec, TaskSpecData, Dict[str, Any]]) -> str:
        if isinstance(task, dict):
            task_obj = TaskSpec(
                task_id=task["task_id"],
                description=task.get("description", ""),
                target_files=task.get("target_files", task.get("target_file", [])),
                dependencies=task.get("dependencies", []),
                test_cmd=task.get("test_cmd", ""),
                status=task.get("status", "pending"),
                assigned_to=task.get("assigned_to", "")
            )
            if isinstance(task_obj.target_files, str):
                task_obj.target_files = [task_obj.target_files] if task_obj.target_files else []
        elif isinstance(task, TaskSpecData):
            task_obj = TaskSpec(
                task_id=task.task_id,
                description=task.description,
                target_files=list(task.target_files),
                dependencies=list(task.dependencies),
                test_cmd=task.test_cmd,
                status=task.status,
                assigned_to=task.assigned_to
            )
        else:
            task_obj = task

        self._tasks[task_obj.task_id] = task_obj
        self._flush()
        return task_obj.task_id

    def update_status(self, task_id: str, status: str) -> None:
        if task_id in self._tasks:
            self._tasks[task_id].status = status
            self._flush()

    def get_task(self, task_id: str) -> Optional[TaskSpec]:
        return self._tasks.get(task_id)

    def get_all_tasks(self) -> List[TaskSpec]:
        return list(self._tasks.values())

    def get_drift(self, root_dir: Union[str, Path] = ".") -> List[DriftReport]:
        """Compare plan tasks vs actual filesystem changes."""
        drift: List[DriftReport] = []
        root = Path(root_dir)

        for tid, task in self._tasks.items():
            # 1. Phantom task: marked done but target file does not exist
            if task.status == "done":
                for f in task.target_files:
                    f_path = root / f
                    if not f_path.exists():
                        drift.append(DriftReport(
                            task_id=tid,
                            drift_type="phantom_completion",
                            detail=f"Task {tid} marked done but target file '{f}' does not exist on disk"
                        ))

            # 2. Undeclared edit: file modified recently but task is pending
            if task.status == "pending":
                for f in task.target_files:
                    f_path = root / f
                    if f_path.exists():
                        try:
                            # If modified in the last 15 minutes
                            if f_path.stat().st_mtime > time.time() - 900:
                                drift.append(DriftReport(
                                    task_id=tid,
                                    drift_type="undeclared_modification",
                                    detail=f"Target file '{f}' modified recently but task {tid} is still pending"
                                ))
                        except Exception:
                            pass

        return drift

    def _flush(self) -> None:
        lines = [
            "# Plans\n\n",
            "> System Execution Plan & Status Tracking Ledger (Generated by Harness TaskLedger)\n\n",
            "| Status | ID | Description | Target Files | Dependencies | Test Command |\n",
            "|:---:|:---:|---|---|---|---|\n"
        ]
        status_icons = {
            "pending": "[ ]",
            "in_progress": "[-]",
            "review": "[R]",
            "done": "[x]",
            "blocked": "[!]"
        }
        for t in self._tasks.values():
            icon = status_icons.get(t.status, "[ ]")
            files = ", ".join(f"`{f}`" for f in t.target_files) if t.target_files else "—"
            deps = ", ".join(t.dependencies) if t.dependencies else "—"
            test = f"`{t.test_cmd}`" if t.test_cmd else "—"
            lines.append(f"| {icon} | {t.task_id} | {t.description} | {files} | {deps} | {test} |\n")

        self.path.parent.mkdir(parents=True, exist_ok=True)
        self.path.write_text("".join(lines), encoding="utf-8")

    def _load_from_file(self) -> None:
        if not self.path.exists():
            return
        content = self.path.read_text(encoding="utf-8")
        status_map = {
            "[ ]": "pending",
            "[-]": "in_progress",
            "[R]": "review",
            "[x]": "done",
            "[!]": "blocked"
        }
        for line in content.splitlines():
            line = line.strip()
            if not line.startswith("|") or "Status" in line or ":---:" in line:
                continue
            parts = [p.strip() for p in line.split("|")[1:-1]]
            if len(parts) >= 6:
                raw_status, tid, desc, raw_files, raw_deps, raw_test = parts[:6]
                status = status_map.get(raw_status, "pending")
                files = [f.strip(" `") for f in raw_files.split(",") if f.strip(" `") and f.strip(" `") != "—"]
                deps = [d.strip() for d in raw_deps.split(",") if d.strip() and d.strip() != "—"]
                test = raw_test.strip(" `") if raw_test.strip(" `") != "—" else ""

                self._tasks[tid] = TaskSpec(
                    task_id=tid,
                    description=desc,
                    target_files=files,
                    dependencies=deps,
                    test_cmd=test,
                    status=status
                )
